openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Film API"
paths:
  /films:
    get:
      summary: "Get all films"
      responses:
        200:
          description: "A list of films"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"
    post:
      summary: "Create a new film"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Film"
      responses:
        201:
          description: "The film was successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
        500:
          description: "Some server error"
  /films/{id}:
    get:
      summary: "Get a film by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the film"
          schema:
            type: string
      responses:
        200:
          description: "The film data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
        404:
          description: "Film not found"
    patch:
      summary: "Update a film by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the film"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Film"
      responses:
        200:
          description: "The film was successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
        500:
          description: "Some server error"
    delete:
      summary: "Delete a film by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the film"
          schema:
            type: string
      responses:
        200:
          description: "The film was successfully deleted"
        500:
          description: "Some server error"
components:
  schemas:
    Film:
      type: object
      required:
        - fields
        - model
      properties:
        fields:
          type: object
          properties:
            starships:
              type: array
              items:
                type: integer
              description: "The starships in the film"
            edited:
              type: string
              description: "The edit date of the film"
            vehicles:
              type: array
              items:
                type: integer
              description: "The vehicles in the film"
            planets:
              type: array
              items:
                type: integer
              description: "The planets in the film"
            producer:
              type: string
              description: "The producer of the film"
            title:
              type: string
              description: "The title of the film"
            created:
              type: string
              description: "The creation date of the film"
            episode_id:
              type: integer
              description: "The episode ID of the film"
            director:
              type: string
              description: "The director of the film"
            release_date:
              type: string
              description: "The release date of the film"
            opening_crawl:
              type: string
              description: "The opening crawl text of the film"
            characters:
              type: array
              items:
                type: integer
              description: "The characters in the film"
            species:
              type: array
              items:
                type: integer
              description: "The species in the film"
        model:
          type: string
          description: "The model of the film"
      example:
        fields:
          starships: [12, 22]
          edited: "2014-12-20T21:23:49.880Z"
          vehicles: [14, 30]
          planets: [1, 2]
          producer: "George Lucas"
          title: "A New Hope"
          created: "2014-12-10T14:23:31.880Z"
          episode_id: 4
          director: "George Lucas"
          release_date: "1977-05-25"
          opening_crawl: "It is a period of civil war..."
          characters: [1, 2]
          species: [1, 2]
        model: "Film"
