openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Planet API"
paths:
  /planets:
    get:
      summary: "Get all planets"
      responses:
        200:
          description: "A list of planets"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Planet"
    post:
      summary: "Create a new planet"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Planet"
      responses:
        201:
          description: "The planet was successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planet"
        500:
          description: "Some server error"
  /planets/{id}:
    get:
      summary: "Get a planet by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the planet"
          schema:
            type: string
      responses:
        200:
          description: "The planet data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planet"
        404:
          description: "Planet not found"
    put:
      summary: "Update a planet by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the planet"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Planet"
      responses:
        200:
          description: "The planet was successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planet"
        500:
          description: "Some server error"
    delete:
      summary: "Delete a planet by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the planet"
          schema:
            type: string
      responses:
        200:
          description: "The planet was successfully deleted"
        500:
          description: "Some server error"
components:
  schemas:
    Planet:
      type: object
      required:
        - fields
        - model
      properties:
        fields:
          type: object
          properties:
            edited:
              type: string
              description: "The edited date of the planet data"
            created:
              type: string
              description: "The creation date of the planet data"
            climate:
              type: string
              description: "The climate of the planet"
            surface_water:
              type: string
              description: "The percentage of the planet surface that is water"
            name:
              type: string
              description: "The name of the planet"
            diameter:
              type: string
              description: "The diameter of the planet"
            rotation_period:
              type: string
              description: "The rotation period of the planet"
            terrain:
              type: string
              description: "The terrain type of the planet"
            gravity:
              type: string
              description: "The gravity of the planet"
            orbital_period:
              type: string
              description: "The orbital period of the planet"
            population:
              type: string
              description: "The population of the planet"
        model:
          type: string
          description: "The model of the planet"
      example:
        fields:
          edited: "2014-12-20T20:58:18.429000Z"
          created: "2014-12-10T11:35:48.479000Z"
          climate: "temperate"
          surface_water: "40"
          name: "Alderaan"
          diameter: "12500"
          rotation_period: "24"
          terrain: "grasslands, mountains"
          gravity: "1 standard"
          orbital_period: "364"
          population: "2000000000"
        model: "Planet"
