openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Species API"
paths:
  /species:
    get:
      summary: "Get all species"
      responses:
        200:
          description: "A list of species"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Species"
    post:
      summary: "Create a new species"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Species"
      responses:
        201:
          description: "The species was successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Species"
        500:
          description: "Some server error"
  /species/{id}:
    get:
      summary: "Get a species by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the species"
          schema:
            type: string
      responses:
        200:
          description: "The species data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Species"
        404:
          description: "Species not found"
    patch:
      summary: "Update a species by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the species"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Species"
      responses:
        200:
          description: "The species was successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Species"
        500:
          description: "Some server error"
    delete:
      summary: "Delete a species by ID"
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the species"
          schema:
            type: string
      responses:
        200:
          description: "The species was successfully deleted"
        500:
          description: "Some server error"
components:
  schemas:
    Species:
      type: object
      required:
        - fields
        - model
      properties:
        fields:
          type: object
          properties:
            edited:
              type: string
              description: "The edited date of the species"
            classification:
              type: string
              description: "The classification of the species"
            name:
              type: string
              description: "The name of the species"
            designation:
              type: string
              description: "The designation of the species"
            created:
              type: string
              description: "The created date of the species"
            eye_colors:
              type: string
              description: "The eye colors of the species"
            skin_colors:
              type: string
              description: "The skin colors of the species"
            language:
              type: string
              description: "The language of the species"
            hair_colors:
              type: string
              description: "The hair colors of the species"
            homeworld:
              type: integer
              description: "The id of the homeworld of the species"
            average_lifespan:
              type: string
              description: "The average lifespan of the species"
            average_height:
              type: string
              description: "The average height of the species"
            people:
              type: array
              items:
                type: integer
              description: "The ids of people belonging to the species"
        model:
          type: string
          description: "The model of the species"
      example:
        fields:
          edited: "2014-12-20T21:36:42.157000Z"
          classification: "mammal"
          name: "Human"
          designation: "sentient"
          created: "2014-12-10T13:52:11.567000Z"
          eye_colors: "brown, blue, green, hazel, grey, amber"
          skin_colors: "caucasian, black, asian, hispanic"
          language: "Galactic Basic"
          hair_colors: "blonde, brown, black, red"
          homeworld: 1
          average_lifespan: "79"
          average_height: "180"
          people: [1, 2, 3, 4]
        model: "Species"
